
server:
  port: 8080

spring:
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/test_db_sharding?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&characterEncoding=utf8
        username: root
        password: 123456
    sharding:
      tables:
        tb_biz_log:
          actual-data-nodes: ds.tb_biz_log_$->{0..3}
          table-strategy:
            inline:
              sharding-column: biz_id
              algorithm-expression: tb_biz_log_$->{biz_id % 4}
          key-generator:
            column: log_id
            type: SNOWFLAKE
            props:
              worker:
                id: 123
      binding-tables: tb_biz_log
mybatis:
  type-aliases-package: top.janker.exp07.shardingjdbc.mybatis.tables.entity
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

knife4j:
  enable: true
  setting:
    # default lang
    language: en-US
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT | [??????](https://www.share-java.com)
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models
